name: NodeJS with Webpack

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Build & Run
      run: bash /home/ubuntu/searchify/searchify-new-ui-portal/scripts/deploy.sh

