name: NodeJS with Webpack

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Stop current process
      run: sudo kill -9 $(sudo lsof -ti:3000)
    - uses: actions/checkout@v3
    - name: Build & Run
      if: ${{ failure() || success() }}
      run: bash /home/ubuntu/searchify/searchify-new-ui-portal/scripts/deploy.sh

